version: "3"

services:
  app-openlist-ultra:
    image: chwjbn/openlist-ultra:prod
    hostname: app-openlist-ultra
    container_name: app-openlist-ultra
    restart: always
    ports:
      - "5244:5244"
    environment:
      - TZ=Asia/Shanghai
      - NOTIFY_WEBHOOK_FEISHU=
      - JELLYFIN_API_HOST=http://192.168.1.100:8096
      - JELLYFIN_API_KEY=
      - JELLYFIN_API_ROOT_FOLDER=/mov
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./etc:/opt/openlist/data:rw"
      - "/mnt:/mnt:rw"
